title: GitSnitch
description: Git operationalization quality assertion framework
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
permalink: pretty
url: "https://iilei.github.io"
baseurl: "/gitsnitch/"
